### ISSUE TITLE
Sane default for Software_Version_Value in software-version.rule

### ISSUE THREAD

**Issue by ConstrainedRandomVar** [Juniper/healthbot-rules#122]
Software version shouldn't be the same as the product. This should be 18.1 or some such..
https://github.com/Juniper/healthbot-rules/blob/master/juniper_official/System/software-version.rule

variable Software_Version_Value {
	value mx960;
	description "Software Version the system should have";
	type string;
}

Regards,

Harsha Lakshmikanth

**Comment by gvarao** [comment]
Harsha..Fixed code is merged, please close the PR.
