### ISSUE TITLE
Typo in microburst rule

### ISSUE THREAD

**Issue by dhineshsj** [Juniper/healthbot-rules#135]
`File` healthbot-rules/juniper_official/Solutions/Microburst/microburst.rule
- Field `microburst` has a typo in the description - `s/valu/value`
- Field `queue_no_expr` has mismatch between type & description. While type is `int`, description says that regex's are allowed. They need to be in sync.

**Comment by gvarao** [comment]
Dinesh..

Fixed code is merged, please close the PR.
