### ISSUE TITLE
show process extensive doesn't work on QFX

### ISSUE THREAD

**Issue by ConstrainedRandomVar** [Juniper/healthbot-rules#148]
The current factory-default YAML file (corresponding to HB 1.0.1) doesn't work on QFX. Including Nitin's fix that works on QFX..

SystemProcExtTable:
    command: show system processes extensive
    key: cmd
    title: '  PID'
    view: SystemProcExtView

SystemProcExtView:
    regex:
        size: '.* \S +(\d+(K|M))\s+'
        res: '(\d+(K|M))'
        wcpu: '.* (\d+\.\d+)%'
        cmd: '\w+'

**Comment by ConstrainedRandomVar** [comment]
Hi Venkat,
 Going forward, can you please include the merge request through which the ticket is addressed?

Regards,

Harsha Lakshmikanth

**Comment by gvarao** [comment]
Hi Harsha,

It is already available. Please click in “merged” icon.

Regards,
Venkat(GV)
