### ISSUE TITLE
Fixes in system KPI rule system-processes-memory.rule

### ISSUE THREAD

**Issue by ConstrainedRandomVar** [Juniper/healthbot-rules#198]
Andrew Duane provided some feedback on our System KPI playbook. 
 - :%s/reserved/resident/g
 - The key needs to also include the PID since the daemon name by itself isn't unambiguous for processes such as mgd, sshd, cli, etc.
 - The python function should be extended to handle GB as well (in addition to parsing KB, HB).

Regards,

Harsha Lakshmikanth

**Comment by ssachinbharadwaj** [comment]
I don't think the below calculation for process memory rule is correct:

```
        if (res/size)*100 >= threshold :
            return True
        else:
            return False
```

It looks like the logic is assuming that SIZE is the max limit and RES is the currently allocated memory.
AFAIK, SIZE is the total current memory of a process and RES is the memory that is in RAM. The maximum limit is defined by RLIMIT
