### ISSUE TITLE
protocol.isis/check-isis-adjacencies

### ISSUE THREAD

**Issue by d200201123** [Juniper/healthbot-rules#252]
As per the “ISIS Openconfig Model”, adjacency-state leaf  gives details of only P2P ISIS adjacency state. 
As the ISIS adjacency in your setup is formed  over a LAN interface, the  state always shows as down.

In rule "protocol.isis/check-isis-adjacencies", trigger isis-adjacency-state always show as down for adjacency formed over  LAN interface.

Update the rule documentation to specify the trigger is only for P2P interface.

Reference : https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang

**Comment by gvarao** [comment]
Modified trigger name to isis-p2p-adjacency-state and committed with PR #263
