### ISSUE TITLE
security.flow/check-flow-session-summary-netconf not generating data

### ISSUE THREAD

**Issue by anaaman** [Juniper/healthbot-rules#271]
When running SRX SA playbook no session data is generated and written to influx db.
Tested on:
SRX320 Junos 15.1X49-D170
vSRX 18.4R2

**Comment by gvarao** [comment]
@anaaman please unicast test setup details and credentials to gvenkata@juniper.net

**Comment by anaaman** [comment]
@gvarao sent by e-mail.

**Comment by gvarao** [comment]
Fixed through pull request #272

**Comment by gvarao** [comment]
Merged
