### ISSUE TITLE
Monitoring QFX5110 18.2R2.6 with Open Config

### ISSUE THREAD

**Issue by anaaman** [Juniper/healthbot-rules#273]
I'm trying to use built-in open-config interface rules on QFX5110 running Junos 18.2R2.
The rules has sensor path starting with /interfaces/... which is not valid for this version.
The right path is for this version starts with : /junos/system/linecard/interface/

Device version information:

Model: qfx5110-48s-4c
Junos: 18.2R2.6 flex
JUNOS OS Kernel 64-bit FLEX [20181108.217da31_builder_stable_11]
JUNOS OS libs [20181108.217da31_builder_stable_11]
JUNOS OS runtime [20181108.217da31_builder_stable_11]
JUNOS OS time zone information [20181108.217da31_builder_stable_11]
JUNOS OS libs compat32 [20181108.217da31_builder_stable_11]
JUNOS OS 32-bit compatibility [20181108.217da31_builder_stable_11]
JUNOS py extensions [20181207.090423_builder_junos_182_r2]
JUNOS py base [20181207.090423_builder_junos_182_r2]
JUNOS OS vmguest [20181108.217da31_builder_stable_11]
JUNOS OS crypto [20181108.217da31_builder_stable_11]
JUNOS network stack and utilities [20181207.090423_builder_junos_182_r2]
JUNOS libs [20181207.090423_builder_junos_182_r2]
JUNOS libs compat32 [20181207.090423_builder_junos_182_r2]
JUNOS runtime [20181207.090423_builder_junos_182_r2]
JUNOS na telemetry [18.2R2.6-C1]
JUNOS Web Management Platform Package [20181207.090423_builder_junos_182_r2]
JUNOS qfx runtime [20181207.090423_builder_junos_182_r2]
JUNOS common platform support [20181207.090423_builder_junos_182_r2]
JUNOS qfx platform support [20181207.090423_builder_junos_182_r2]
JUNOS dcp network modules [20181207.090423_builder_junos_182_r2]
JUNOS modules [20181207.090423_builder_junos_182_r2]
JUNOS qfx modules [20181207.090423_builder_junos_182_r2]
JUNOS qfx Data Plane Crypto Support [20181207.090423_builder_junos_182_r2]
JUNOS daemons [20181207.090423_builder_junos_182_r2]
JUNOS qfx daemons [20181207.090423_builder_junos_182_r2]
JUNOS SDN Software Suite [20181207.090423_builder_junos_182_r2]
JUNOS Extension Toolkit [20181207.090423_builder_junos_182_r2]
JET app jpuppet [3.6.1_4.0]
JUNOS Packet Forwarding Engine Support (DC-PFE) [20181207.090423_builder_junos_182_r2]
JUNOS Packet Forwarding Engine Support (M/T Common) [20181207.090423_builder_junos_182_r2]
JUNOS J-Insight [20181207.090423_builder_junos_182_r2]
JUNOS jfirmware [20181207.090423_builder_junos_182_r2]
JUNOS Online Documentation [20181207.090423_builder_junos_182_r2]
JUNOS jail runtime [20181108.217da31_builder_stable_11]
JUNOS FIPS mode utilities [20181207.090423_builder_junos_182_r2]
JET app chef [11.10.4_3.0]
JUNOS Host Software [3.14.52-rt50-WR7.0.0.9_ovp:3.0.9]
JUNOS Host qfx-5e host-control package [18.2R2.6]
JUNOS Host qfx-5e host-platform package [18.2R2.6]
JUNOS Host qfx-5e control-plane flex package [18.2R2.6]
JUNOS Host qfx-5e platform package [18.2R2.6]
JUNOS Host qfx-5e base package [18.2R2.6]
JUNOS Host qfx-5e data-plane package [18.2R2.6]
Junos for Automation Enhancement

**Comment by gowrisankarvs** [comment]
Healthbot packages are created based on latest Junos release OpenConfig paths. Please refer the following link for supported OC paths.

https://apps.juniper.net/telemetry-explorer/explore?software=Junos%20OS&release=18.2R1&moduleId=All

You are actually referring to Native GPB sensor to collect the information for PFE directly.

Thanks,
Gowrisankar

**Comment by anaaman** [comment]
Hello Gowrisankar
I'll can check this tomorrow and drop you an e-mail with the rule and the errors from the QFX log.

Best regrads

**Comment by gvarao** [comment]
Invalid PR
