### ISSUE TITLE
system.alarm/check-chassis-alarms display incorrect status

### ISSUE THREAD

**Issue by anaaman** [Juniper/healthbot-rules#278]
Hi,
The system.alarm/check-chassis-alarms has the following issues:
When no alarms on device - the topic has no status (gray).
When system has minor alarm - the topic has red status.

Test Env.
SRX345 SA Junos 18.2R3.4.
To create the alarm I just deleted the rescue config.

**Comment by gvarao** [comment]
Hi
Thanks for opening issue. It is done purposely i.e. if  no-alarms then it is gray, if any class of alarm then its red. If you feel it doesn't make sense then suggest the better approach.

**Comment by anaaman** [comment]
Hi
I will think about other approach and drop you an e-mail.
