### ISSUE TITLE
In Rule "check-vmhost-cpu-iagent" yml file needs to be modified by removing "gnice" 

### ISSUE THREAD

**Issue by bmadhavi74** [Juniper/healthbot-rules#296]
Data not coming for gnice, if i delete it from yml file then it will work properly.

---
VMhostCPUTable:
  command: show vmhost resource-usage
  key: cpu
  title: 'CPU Usage'
  view: VMhostCPUView

VMhostCPUView:
  regex:
    ts: '\d{2}:\d{2}:\d{2}'
    cpu: \w+
    usr: '\d+\.\d+'
    nice: '\d+\.\d+'
    sys: '\d+\.\d+'
    iowait: '\d+\.\d+'
    irq: '\d+\.\d+'
    soft: '\d+\.\d+'
    steal: '\d+\.\d+'
    guest: '\d+\.\d+'
    gnice: '\d+\.\d+'
    idle: '\d+\.\d+'

**Comment by gvarao** [comment]
Fixed via PR #297
