### ISSUE TITLE
EX check-interface-bandwidth-netconf incorrect settings

### ISSUE THREAD

**Issue by anaaman** [Juniper/healthbot-rules#322]
The rule has two function files:
bw_util_percent.py
mbps_conversion.py
The files does not exists in the git.
There is a function file bw_utilization.py which has the required functions.
Can you please verify?

**Comment by gvarao** [comment]
modified rule file with in built go lang functions. please check now.. btw rule file moved to /Interfaces folder as now it is platform agnostic

**Comment by anaaman** [comment]
Thanks
Will check it out.
