### ISSUE TITLE
snmp-interface-throughput.rule cannot be loaded in Healthbot 3.0.0

### ISSUE THREAD

**Issue by Jaywwwww** [Juniper/healthbot-rules#329]
it is mentioned below content has error
It seems "eval" is no longer supported in Healthbot 3.0.0
           field in-bw-util {
                formula {
                    eval {
                        expression "($in-mbps / $if-speed ) * 100";
                    }
                }
                type float;
                description "Input bandwidth utilization";
            }
            field out-bw-util {
                formula {
                    eval {
                        expression "($out-mbps / $if-speed ) * 100";
                    }
                }
                type float;
                description "Output bandwidth utilization";
            }

**Comment by gvarao** [comment]
I am sorry..This feature is available from upcoming release 3.1.0. In case you want build download from /volume/healthbot/build/CD/development from any shell servers. ignore latest_stable and take image something build in august.

**Comment by Jaywwwww** [comment]
Hi , 

May I know what is release date of Healthbot 3.1.0? I just installed 3.0.1 for testing....

**Comment by gvarao** [comment]
It will work only on HB 3.1.0
