### ISSUE TITLE
Where is speed-conversion.py file which called in snmp-interface-throughput.rule

### ISSUE THREAD

**Issue by Jaywwwww** [Juniper/healthbot-rules#330]
Where is speed-conversion.py file which called in snmp-interface-throughput.rule ?

**Comment by gvarao** [comment]
Hi.. It is available in https://github.com/Juniper/healthbot-rules/blob/master/juniper_official/Interfaces/speed-conversion.py

**Comment by Jaywwwww** [comment]
Thanks!
