### ISSUE TITLE
Inconsistent naming convention between netconf / iAgent

### ISSUE THREAD

**Issue by valjeanchan** [Juniper/healthbot-rules#351]
Inconsistent naming convention between netconf / iAgent rules:

interface.statistics/check-out-errors-netconf
interface.statistics/check-in-errors-iagent

**Comment by gvarao** [comment]
Fixed in latest 3.1.0

**Comment by gvarao** [comment]
You are right. All new rules will follow -netconf. Old rules cann't be modified due to backward compatibility issue with playbooks
