### ISSUE TITLE
Unable to upload interface.statistics/check-interface-bandwidth-netconf

### ISSUE THREAD

**Issue by anaaman** [Juniper/healthbot-rules#387]
I'm trying to upload the rule file:
interface.statistics/check-interface-bandwidth-netconf
and receive the error message:

Failed to upload files. Failed to update topics and rules from check-interface-bandwidth-netconf.rule.. ConfigLoadError: ConfigLoadError(severity: error, bad_element: eval, message: error: syntax error error: error recovery ignores input until this point warning: mgd: statement has no contents; ignored error: error recovery ignores input until this point warning: mgd: statement has no contents; ignored)

Healthbot version 3.0.1

**Comment by gvarao** [comment]
Fixed in #352
