### ISSUE TITLE
RES memory - :%s/reserved/resident/

### ISSUE THREAD

**Issue by ConstrainedRandomVar** [Juniper/healthbot-rules#453]
In https://github.com/Juniper/healthbot-rules/blob/master/juniper_official/System/system-processes-memory.rule, can we change all instances of reserved to resident?

      field res {
                sensor systemprocexttable {
                    path res;
                }
                type string;
                description "Reserved memory of daemon";
            }

Regards,

Harsha Lakshmikanth

**Comment by gvarao** [comment]
Fixed in #457

**Comment by gvarao** [comment]
Code merged in development branch. Please check and revert
