### ISSUE TITLE
chassis.power/check-zone-power-usage not supported on QFX

### ISSUE THREAD

**Issue by d200201123** [Juniper/healthbot-rules#502]
The rule chassis.power/check-zone-power-usage is not supported on QFX platform.
product name need to be removed from the list of supported devices in Rule properties.

![image](https://user-images.githubusercontent.com/15723582/109486381-ce598600-7aa8-11eb-8e5d-a1d8036b8102.png)

**Comment by gvarao** [comment]
fixed with PR #550
